### ISSUE TITLE
`/apps`: SEO (as it's a big source of new users)

### ISSUE THREAD

**Issue by WofWca** [webxdc/website#53]
I think that https://webxdc.org/apps/ might be a very important page and a big source of user traction, especially of potential new users of Delta Chat. Why? Because this is an app store, and collectively the apps cover a large amount of search queries. For example, a search for "collaborative text editor" should show this page.
Being a super-app is a big selling point of Delta Chat, and other webxdc-runtime messengers.

So, to be more specific:
- [ ] Each app must have a separate page. I know the list is generated client-site, but IIRC at least Google is capable of crawling PWA pages. Maybe we could also consider server-side rendering (SSR). At the very least we need to add a router, like in React and Vue.
- [ ] The page should be self-contained, without assuming that users know what Delta Chat or webxdc is.
- [ ] https://github.com/webxdc/website/blob/d8ee4e484fe6fd57d46a7c488e30aa315e9c94fc/apps/index.html#L7

**Comment by rosano** [comment]
>  The page should be self-contained, without assuming that users know what Delta Chat or webxdc is.

In terms of this point specifically, I think @hpk42 did mention there's an assumption of familiarity, likely people already using webxdc.

**Comment by rosano** [comment]
>  The page should be self-contained, without assuming that users know what Delta Chat or webxdc is.

In terms of this point specifically, I think @hpk42 did mention there's an assumption of familiarity, likely people already using webxdc.

**Comment by hpk42** [comment]
yes, webxdc.org is to not focus much on Delta Chat, but point to it and cheogram respectively. 
Anyways, this issue is out of scope for now.   The /apps are good already as they are. 
Revising webxdc.org internal linking is what is upcoming.  

Please note that the general idea of this issue tracker to track agreed-on things (by more than one person, more like 2-3) and file bugs or directly improvement-PRs. webxdc will get a bigger focus again next year, for now we are just maintaining and revising a little what we have.
